# Generated by Django 6.0.3 on 2026-04-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_seed_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload supporting documents (optional)', null=True, upload_to='leave_attachments/%Y/%m/'),
        ),
    ]
