# Generated by Django 6.0.3 on 2026-04-10 08:12

import leave.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload supporting documents (optional)', null=True, upload_to=leave.models.leave_attachment_path),
        ),
    ]
