# Generated by Django 6.0.3 on 2026-04-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_attachment'),
    ]

    operations = [
    ]
