# Generated by Django 6.0.3 on 2026-04-22 12:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_carusage_unique_together_carusage_intervention_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelecomSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='Site Name')),
                ('site_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Site Code')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address', models.CharField(max_length=500, verbose_name='Address')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Telecom Site',
                'verbose_name_plural': 'Telecom Sites',
                'ordering': ['site_name'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codice_nigit', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Codice NIGIT')),
                ('oda', models.CharField(blank=True, max_length=100, verbose_name='ODA')),
                ('anno_intervento', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Anno')),
                ('cliente', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Cliente')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Intervento')),
                ('assistente', models.CharField(blank=True, max_length=200, verbose_name='Nome Assistente')),
                ('data_richiesta', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Richiesta')),
                ('tipologia_intervento', models.CharField(blank=True, max_length=100, verbose_name='Tipologia Intervento')),
                ('ticket', models.CharField(blank=True, max_length=100, verbose_name='Ticket')),
                ('international_code', models.CharField(blank=True, max_length=50, verbose_name='International Code')),
                ('codice_sito', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Codice Sito')),
                ('data_assegnazione_squadra', models.DateField(blank=True, null=True, verbose_name='Data Assegnazione Squadra')),
                ('extra_info', models.CharField(blank=True, max_length=200, verbose_name='Extra Info')),
                ('stato_avanzamento_nigit', models.CharField(blank=True, choices=[('', '---------'), ('DA_INIZIARE', 'Da Iniziare'), ('IN_CORSO', 'In Corso'), ('SOSPESO', 'Sospeso'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], db_index=True, max_length=20, verbose_name='Stato Avanzamento NIGIT')),
                ('stato_avanzamento_contabile_nigit', models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Avanzamento Contabile NIGIT')),
                ('stato_contabile_sirti', models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Contabile Sirti')),
                ('stato_contabile_da_nigit_a_cliente', models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Contabile da NIGIT a Cliente')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data_chiusura_lavori', models.DateField(blank=True, null=True, verbose_name='Data Chiusura Lavori')),
                ('data_invio_preventivo', models.DateField(blank=True, null=True, verbose_name='Data Invio Preventivo')),
                ('data_approvazione_preventivo', models.DateField(blank=True, null=True, verbose_name='Data Approvazione Preventivo')),
                ('tot_richiesto', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tot Richiesto')),
                ('importo_autorizzato_sirti', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importo Autorizzato Sirti')),
                ('differenza_dare_avere', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Differenza Dare/Avere')),
                ('ses_sirti', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='SES Sirti')),
                ('assigned_employees', models.ManyToManyField(blank=True, db_index=True, related_name='interventions_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_created', to=settings.AUTH_USER_MODEL)),
                ('used_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='fleet.car')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['codice_nigit', 'created_at'], name='interventio_codice__ae1122_idx'), models.Index(fields=['cliente', 'anno_intervento'], name='interventio_cliente_a2b234_idx'), models.Index(fields=['stato_avanzamento_nigit', 'data_richiesta'], name='interventio_stato_a_f959f8_idx'), models.Index(fields=['codice_sito'], name='interventio_codice__8d687e_idx')],
            },
        ),
    ]
