# Generated by Django 6.0.3 on 2026-04-03 09:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be in format INT-00001', regex='^INT-\\d{5}$')])),
                ('intervention_type', models.CharField(db_index=True, default='maintenance', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Contains all data from Google Sheets')),
                ('is_synced', models.BooleanField(default=False)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('assigned_employees', models.ManyToManyField(blank=True, db_index=True, related_name='interventions_assigned', to=settings.AUTH_USER_MODEL)),
                ('used_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='fleet.car')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'created_at'], name='interventio_code_c9504b_idx'), models.Index(fields=['intervention_type', 'created_at'], name='interventio_interve_b88192_idx'), models.Index(fields=['is_synced', 'last_synced'], name='interventio_is_sync_64e1ef_idx')],
            },
        ),
    ]
