# Generated by Django 6.0.3 on 2026-04-07 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_carusage_unique_together_carusage_intervention_and_more'),
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='intervention',
            name='interventio_code_c9504b_idx',
        ),
        migrations.RemoveIndex(
            model_name='intervention',
            name='interventio_interve_b88192_idx',
        ),
        migrations.RemoveIndex(
            model_name='intervention',
            name='interventio_is_sync_64e1ef_idx',
        ),
        migrations.AddField(
            model_name='intervention',
            name='anno_intervento',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Anno Intervento'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='assistente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Assistente'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cliente',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='codice_nigit',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Codice NIGIT'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='codice_sito',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Codice Sito'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='data_approvazione_preventivo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Approvazione Preventivo'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='data_assegnazione_squadra',
            field=models.DateField(blank=True, null=True, verbose_name='Data Assegnazione Squadra'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='data_chiusura_lavori',
            field=models.DateField(blank=True, null=True, verbose_name='Data Chiusura Lavori'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='data_invio_preventivo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Invio Preventivo'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='data_richiesta',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data Richiesta'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='differenza_dare_avere',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Differenza Dare/Avere'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='importo_autorizzato_sirti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importo Autorizzato Sirti'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='international_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='International Code'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='oda',
            field=models.CharField(blank=True, max_length=100, verbose_name='ODA'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='ses_sirti',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='SES Sirti'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='stato_avanzamento_contabile_nigit',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Avanzamento Contabile NIGIT'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='stato_avanzamento_nigit',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DA_INIZIARE', 'Da Iniziare'), ('IN_CORSO', 'In Corso'), ('SOSPESO', 'Sospeso'), ('COMPLETATO', 'Completato'), ('ANNULLATO', 'Annullato')], db_index=True, max_length=20, verbose_name='Stato Avanzamento NIGIT'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='stato_contabile_da_nigit_a_cliente',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Contabile da NIGIT a Cliente'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='stato_contabile_sirti',
            field=models.CharField(blank=True, choices=[('', '---------'), ('DA_EMETTERE', 'Da Emettere'), ('EMESSO', 'Emesso'), ('INVIATO', 'Inviato'), ('APPROVATO', 'Approvato'), ('PAGATO', 'Pagato'), ('CONTABILIZZATO', 'Contabilizzato')], db_index=True, max_length=20, verbose_name='Stato Contabile Sirti'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='ticket',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='tipologia_intervento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipologia Intervento'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='tot_richiesto',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tot Richiesto'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['codice_nigit', 'created_at'], name='interventio_codice__ae1122_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['cliente', 'anno_intervento'], name='interventio_cliente_a2b234_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['stato_avanzamento_nigit', 'data_richiesta'], name='interventio_stato_a_f959f8_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['codice_sito'], name='interventio_codice__8d687e_idx'),
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='code',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='data',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='intervention_type',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='is_synced',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='last_synced',
        ),
    ]
