# Generated by Django 6.0.3 on 2026-04-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_update_intervention_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='anno_intervento',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Anno'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='assistente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Assistente'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intervento'),
        ),
    ]
