# Generated by Django 6.0.3 on 2026-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_alter_intervention_anno_intervento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='codice_nigit',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Codice NIGIT'),
        ),
    ]
