# Generated by Django 6.0.3 on 2026-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_alter_intervention_codice_nigit_telecomsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='extra_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Extra Info'),
        ),
    ]
