# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="incoming_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="in_transit_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="item",
            name="position_area",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="position_detail",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="position_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="position_shelf",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="supplier_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="unit_of_measure",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="item",
            name="used_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
