# Generated by Django 5.2.1 on 2026-05-26 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_excel_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, help_text="This supplier's own SKU / part number for the item", max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Purchase / cost price from THIS supplier (different suppliers can have different prices)', max_digits=10)),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as the default/preferred supplier when buying this item')),
                ('lead_time_days', models.PositiveIntegerField(default=0, help_text='Typical number of days from order to delivery from this supplier')),
                ('min_order_quantity', models.PositiveIntegerField(default=1, help_text='Smallest quantity this supplier is willing to sell')),
                ('notes', models.TextField(blank=True, help_text='Any special terms, discounts, contracts, or ordering notes for this supplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_details', to='warehouse.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_suppliers', to='warehouse.supplier')),
            ],
            options={
                'verbose_name': 'Item Supplier',
                'verbose_name_plural': 'Item Suppliers',
                'ordering': ['-is_preferred', 'supplier__name'],
                'unique_together': {('item', 'supplier')},
            },
        ),
    ]
