# Generated by Django 5.2.1 on 2026-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_itemsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsupplier',
            name='description',
            field=models.TextField(blank=True, help_text="This supplier's description or specifications for the item"),
        ),
    ]
