# Generated by Django 5.2.1 on 2026-05-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_itemsupplier_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='supplier_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit_price',
        ),
    ]
