# Generated by Django 5.2.1 on 2026-05-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_supplier_options_remove_item_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode/QR code for scanning', max_length=50),
        ),
    ]
