# Generated by Django 5.2.1 on 2026-05-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_warehousezone_auditlog_stocktaking_stocktakingitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='warehouse.warehousezone'),
        ),
    ]
