# Generated by Django 5.2.1 on 2026-05-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_alert',
            field=models.BooleanField(default=True, help_text='Send email alert when stock falls below minimum'),
        ),
    ]
