# Generated by Django 5.2.1 on 2026-05-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_item_low_stock_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('on_time_deliveries', models.IntegerField(default=0)),
                ('late_deliveries', models.IntegerField(default=0)),
                ('quality_issues', models.IntegerField(default=0)),
                ('average_lead_time', models.DecimalField(decimal_places=2, default=0, help_text='Average lead time in days', max_digits=5)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Rating from 0 to 5', max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='warehouse.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Performance',
                'verbose_name_plural': 'Supplier Performances',
                'unique_together': {('supplier',)},
            },
        ),
    ]
