# Generated by Django 5.2.1 on 2026-05-26 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_item_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouserequest',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='quantity_approved',
        ),
        migrations.RemoveField(
            model_name='warehouserequest',
            name='quantity_requested',
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='WarehouseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.IntegerField()),
                ('quantity_approved', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.item')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
