# Generated by Django 6.0.3 on 2026-04-10 08:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_employeeasset_employeedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=accounts.models.employee_document_path),
        ),
    ]
