# Generated by Django 6.0.3 on 2026-04-10 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_employeedocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('leave_request', 'Leave Request'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('attendance_late', 'Late Check-in'), ('attendance_absent', 'Absent'), ('attendance_missing_checkout', 'Missing Check-out'), ('assignment_new', 'New Assignment'), ('assignment_status_change', 'Assignment Status Change'), ('assignment_deadline', 'Assignment Deadline'), ('intervention_new', 'New Intervention'), ('intervention_status_change', 'Intervention Status Change'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'), models.Index(fields=['-created_at'], name='accounts_no_created_4d1468_idx')],
            },
        ),
    ]
