# Generated by Django 6.0.3 on 2026-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('ex_employee', 'Ex-Employee')], db_index=True, default='employee', max_length=20),
        ),
    ]
