# Generated by Django 6.0.3 on 2026-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employeeskill_is_verified_employeeskill_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode for user interface'),
        ),
    ]
