# Generated by Django 6.0.3 on 2026-04-22 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_dark_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('staff', 'Staff Only'), ('managers', 'Managers Only'), ('admin', 'Admin Only')], default='all', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['-priority', '-created_at'], name='accounts_an_priorit_3700d6_idx'), models.Index(fields=['is_active', 'start_date', 'end_date'], name='accounts_an_is_acti_cc0eb9_idx')],
            },
        ),
    ]
