# Generated by Django 6.0.3 on 2026-04-22 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('attendance', 'Attendance Stats'), ('assignments', 'Recent Assignments'), ('announcements', 'Announcements'), ('messages', 'Unread Messages'), ('leave', 'Leave Balance'), ('notifications', 'Notifications'), ('quick_actions', 'Quick Actions'), ('calendar', 'Calendar')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-grid', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_widgets', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='accounts.widget')),
            ],
            options={
                'verbose_name': 'User Widget',
                'verbose_name_plural': 'User Widgets',
                'ordering': ['order'],
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
