# Generated by Django 6.0.3 on 2026-04-22 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_widget_userwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('link', 'External Link'), ('page', 'Internal Page'), ('function', 'JavaScript Function')], max_length=50)),
                ('url', models.URLField(blank=True, help_text='For link and page actions')),
                ('icon', models.CharField(default='bi-lightning', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Action',
                'verbose_name_plural': 'Quick Actions',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserQuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quick_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_configs', to='accounts.quickaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quick_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Quick Action',
                'verbose_name_plural': 'User Quick Actions',
                'ordering': ['order'],
                'unique_together': {('user', 'quick_action')},
            },
        ),
    ]
