# Generated by Django 6.0.3 on 2026-04-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carusage',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_usage', to='interventions.intervention'),
        ),
        migrations.AlterUniqueTogether(
            name='carusage',
            unique_together={('car', 'intervention', 'employee', 'date')},
        ),
    ]
