# Generated by Django 6.0.3 on 2026-04-07 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_carusage_unique_together_carusage_intervention_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codice_nigit', models.CharField(db_index=True, max_length=50, verbose_name='Codice NIGIT')),
                ('assignment_note', models.TextField(help_text='Instructions for the employee', verbose_name='Assignment Note')),
                ('site_address', models.TextField(blank=True, verbose_name='Site Address')),
                ('site_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Site Latitude')),
                ('site_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Site Longitude')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Assigned Date')),
                ('scheduled_date', models.DateTimeField(blank=True, help_text='When the work should be performed', null=True, verbose_name='Scheduled Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('assigned_to', models.ForeignKey(limit_choices_to={'groups__name__in': ['Employee', 'Manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='work_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_assignment', to='interventions.intervention', verbose_name='Intervention')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_assignments', to='fleet.car', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Work Assignment',
                'verbose_name_plural': 'Work Assignments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='assignments_assigne_d4ae3a_idx'), models.Index(fields=['status', 'assigned_date'], name='assignments_status_824849_idx'), models.Index(fields=['codice_nigit'], name='assignments_codice__5e46c1_idx')],
            },
        ),
    ]
