# Generated by Django 6.0.3 on 2026-04-07 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_workassignment_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workassignment',
            name='assignments_assigne_d4ae3a_idx',
        ),
        migrations.RemoveField(
            model_name='workassignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workassignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='work_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
