# Generated by Django 6.0.3 on 2026-04-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_remove_workassignment_assignments_assigne_d4ae3a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Completed By'),
        ),
        migrations.AddField(
            model_name='workassignment',
            name='completion_note',
            field=models.TextField(blank=True, help_text='Notes about work completion', verbose_name='Completion Note'),
        ),
    ]
