# Generated by Django 6.0.3 on 2026-04-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_workassignment_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignment',
            name='work_performed',
            field=models.BooleanField(default=True, help_text='Indicates if the work was actually completed', verbose_name='Work Performed'),
        ),
    ]
