# Generated by Django 6.0.3 on 2026-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_workassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_worked', 'Not Worked'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
