# Generated by Django 6.0.3 on 2026-04-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_alter_workassignment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('work_completed', 'Work Completed'), ('not_worked', 'Not Worked')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
