# Generated by Django 6.0.3 on 2026-05-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='break_duration',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Break duration in hours (default: 1 hour)', max_digits=5),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this attendance record is approved (for manual entries)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about attendance'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Overtime hours beyond standard 8 hours', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='standard_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Standard work hours per day (default: 8 hours)', max_digits=7),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], db_index=True, default='present', max_length=20),
        ),
    ]
