# Generated by Django 6.0.3 on 2026-04-22 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('standard_working_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard working hours per day.', max_digits=4)),
                ('check_in_cutoff', models.TimeField(default='09:00', help_text='Time after which employee is considered late.')),
                ('check_out_cutoff', models.TimeField(default='17:00', help_text='Time before which employee is considered early departure.')),
                ('grace_period_minutes', models.IntegerField(default=15, help_text='Grace period in minutes for late arrival.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policies',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_departure_minutes',
            field=models.IntegerField(default=0, help_text='Number of minutes early (before check-out cutoff).'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0, help_text='Number of minutes late (after check-in cutoff).'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes for policy violations or corrections.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours beyond standard working hours.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_departure', 'Early Departure'), ('half_day', 'Half Day')], db_index=True, default='present', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendance__user_id_c01e0c_idx'),
        ),
    ]
