# Generated by Django 6.0.3 on 2026-04-22 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancepolicy_attendance_early_departure_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendancePolicy',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='early_departure_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_location',
            field=models.CharField(blank=True, help_text='Location where check-in was performed.', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_location',
            field=models.CharField(blank=True, help_text='Location where check-out was performed.', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_early_departure',
            field=models.BooleanField(default=False, help_text='Whether the employee departed early.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late_arrival',
            field=models.BooleanField(default=False, help_text='Whether the employee arrived late.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Whether this attendance record includes overtime.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='minutes_early',
            field=models.PositiveIntegerField(default=0, help_text='Minutes departed early beyond allowed grace period.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='minutes_late',
            field=models.PositiveIntegerField(default=0, help_text='Minutes late beyond allowed grace period.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours calculated beyond standard work hours.', max_digits=7),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_overtime'], name='attendance__is_over_e1bcd6_idx'),
        ),
    ]
