# Generated by Django 6.0.3 on 2026-04-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_delete_attendancepolicy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_location',
        ),
    ]
