# Generated by Django 6.0.3 on 2026-04-22 10:43

from django.db import migrations, connection


def drop_column_if_exists(apps, schema_editor):
    """Drop check_in_location column if it exists."""
    with connection.cursor() as cursor:
        # Check if the column exists
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='attendance_attendance' 
                AND column_name='check_in_location'
            """)
            if cursor.fetchone():
                cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN check_in_location;")
        else:
            # For SQLite, try to drop and ignore if it doesn't exist
            cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN check_in_location;")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20260422_1242'),
    ]

    operations = [
        migrations.RunPython(drop_column_if_exists, migrations.RunPython.noop),
    ]
