# Generated by Django 6.0.3 on 2026-04-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20260422_1242'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN check_in_location;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
