# Generated by Django 6.0.3 on 2026-04-22 10:46

from django.db import migrations, connection


def drop_column_if_exists(apps, schema_editor):
    """Drop check_out_location column if it exists."""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='attendance_attendance' 
                AND column_name='check_out_location'
            """)
            if cursor.fetchone():
                cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN check_out_location;")
        else:
            cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN check_out_location;")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20260422_1243'),
    ]

    operations = [
        migrations.RunPython(drop_column_if_exists, migrations.RunPython.noop),
    ]
