# Generated by Django 6.0.3 on 2026-04-22 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20260422_1243'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN check_out_location;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
