# Generated by Django 6.0.3 on 2026-04-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20260422_1246'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN is_early_departure;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
