# Generated by Django 6.0.3 on 2026-04-22 10:47

from django.db import migrations, connection


def drop_column_if_exists(apps, schema_editor):
    """Drop is_late_arrival column if it exists."""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='attendance_attendance' 
                AND column_name='is_late_arrival'
            """)
            if cursor.fetchone():
                cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN is_late_arrival;")
        else:
            cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN is_late_arrival;")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20260422_1247'),
    ]

    operations = [
        migrations.RunPython(drop_column_if_exists, migrations.RunPython.noop),
    ]
