# Generated by Django 6.0.3 on 2026-04-22 10:47

from django.db import migrations, connection


def drop_index_and_column_if_exists(apps, schema_editor):
    """Drop index and is_overtime column if they exist."""
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            # Check if column exists
            cursor.execute("""
                SELECT column_name 
                FROM information_schema.columns 
                WHERE table_name='attendance_attendance' 
                AND column_name='is_overtime'
            """)
            if cursor.fetchone():
                cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN is_overtime;")
        else:
            # For SQLite, try to drop and ignore if it doesn't exist
            try:
                cursor.execute("DROP INDEX IF EXISTS attendance__is_over_e1bcd6_idx;")
            except:
                pass
            cursor.execute("ALTER TABLE attendance_attendance DROP COLUMN is_overtime;")


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20260422_1247'),
    ]

    operations = [
        migrations.RunPython(drop_index_and_column_if_exists, migrations.RunPython.noop),
    ]
