# Generated by Django 6.0.3 on 2026-04-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20260422_1247'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP INDEX IF EXISTS attendance__is_over_e1bcd6_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN is_overtime;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
