# Generated by Django 6.0.3 on 2026-04-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_auto_20260422_1247'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN minutes_early;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
