# Generated by Django 6.0.3 on 2026-04-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20260422_1248'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE attendance_attendance DROP COLUMN minutes_late;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
