# Generated by Django 6.0.3 on 2026-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20260422_1249'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__user_id_c01e0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__is_over_e1bcd6_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], db_index=True, default='present', max_length=20),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_early_departure',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late_arrival',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_overtime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minutes_early',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minutes_late',
        ),
    ]
