# Generated by Django 6.0.3 on 2026-04-22 12:55

from django.db import migrations, models, connection


def remove_fields_if_exist(apps, schema_editor):
    """Remove fields only if they exist in the database."""
    fields_to_remove = [
        'check_out_location',
        'is_early_departure',
        'is_late_arrival',
        'is_overtime',
        'minutes_early',
        'minutes_late'
    ]
    
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            for field in fields_to_remove:
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name='attendance_attendance' 
                    AND column_name=%s
                """, [field])
                if cursor.fetchone():
                    cursor.execute(f"ALTER TABLE attendance_attendance DROP COLUMN {field};")
        else:
            # For SQLite, try to drop and ignore if it doesn't exist
            for field in fields_to_remove:
                try:
                    cursor.execute(f"ALTER TABLE attendance_attendance DROP COLUMN {field};")
                except:
                    pass


def remove_indexes_if_exist(apps, schema_editor):
    """Remove indexes only if they exist."""
    indexes_to_remove = [
        'attendance__user_id_c01e0c_idx',
        'attendance__is_over_e1bcd6_idx'
    ]
    
    with connection.cursor() as cursor:
        if connection.vendor == 'postgresql':
            for index in indexes_to_remove:
                cursor.execute("""
                    SELECT indexname 
                    FROM pg_indexes 
                    WHERE tablename='attendance_attendance' 
                    AND indexname=%s
                """, [index])
                if cursor.fetchone():
                    cursor.execute(f"DROP INDEX IF EXISTS {index};")
        else:
            # For SQLite
            for index in indexes_to_remove:
                try:
                    cursor.execute(f"DROP INDEX IF EXISTS {index};")
                except:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20260422_1249'),
    ]

    operations = [
        migrations.RunPython(remove_indexes_if_exist, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], db_index=True, default='present', max_length=20),
        ),
        migrations.RunPython(remove_fields_if_exist, migrations.RunPython.noop),
    ]
