# Generated by Django 6.0.3 on 2026-04-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_attendance_attendance__user_id_c01e0c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__user_id_c01e0c_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__is_over_e1bcd6_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_location',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_early_departure',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_late_arrival',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_overtime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minutes_early',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='minutes_late',
        ),
    ]
